### ISSUE TITLE
Import wonkiness

### ISSUE THREAD

**Issue by donspaulding** [IrvingA5106/APCSP_Zork_Thingie#2]
Hey, I'm Don.  I'm Jon's brother.  I was looking over your code and had one suggestion you might want to consider.

It looks like you have a missing import of Player here:

https://github.com/IrvingA5106/APCSP_Zork_Thingie/blob/master/basement.py#L42

Also, that line hijacks control from the main module such that `startGame` is never called.  If you want to use that line for testing, you may want to surround this line (and any similar lines in other modules) with something like this:

```python
if __name__ == "__main__":
    basement(Player())
```

This will make it so the code only runs when it's the main module, not every time it gets imported.

Cool game, keep up the good work!

**Comment by MggMuggins** [comment]
We've not been doing enough testing as we develop, that's sorta born out of the haphazard way this project got started, learning git at the same time, you know.

I was considering setting up that if statement but I didn't remember the exact syntax, and didn't think it was super important. Python is far cry from Rust :D
